theme: jekyll-theme-minimal
title: Rud Merriam
description: A retired guy keeping his brain active with C++

baseurl: ""

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


# from https://github.com/barryclark/jekyll-now/blob/master/_config.yml
