theme: jekyll-theme-minimal
title: Rud Merriam
description: A retired guy keeping his brain active with C++

baseurl: ""

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

footer-links:
  twitter: rmerriam
  linkedin: www.linkedin.com/in/rud-merriam




# from https://github.com/barryclark/jekyll-now/blob/master/_config.yml
